# Generated by Django 3.1.6 on 2021-02-01 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeedata', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
